Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2023-06, with the labels that each got.

#576 Implement streaming for source file parsing
  src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
  src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/main/java/org/openrewrite/maven/ResourceParser.java
Labels: enhancement

#577 Remove unwanted characters from error message
  src/main/java/org/openrewrite/maven/ResourceParser.java
Labels: bug

#585 Jackson 2.15.2
  pom.xml
Labels: dependencies

#586 Bump Netty to 4.1.94 & Rsocket to 1.1.4
  pom.xml
Labels: dependencies
