Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2023-12, with the labels that each got.

#672 Improve quark parsing message
  src/main/java/org/openrewrite/maven/ResourceParser.java
Labels: documentation, enhancement

#673 Avoid annotation processor warning
  .github/workflows/ci.yml
  pom.xml
Labels: enhancement

#677 Always parse Maven wrapper files
  .sdkmanrc
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Labels: bug

#683 Reuse ExecutionContext for ResourceParser
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/main/java/org/openrewrite/maven/ResourceParser.java
Labels: enhancement

#690 Revert to Java 17 after openrewrite/rewrite#3826
  .github/workflows/bump-snapshots.yml
  .github/workflows/ci.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
  .sdkmanrc
  pom.xml
Labels: bug
