Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2023-11, with the labels that each got.

#663 Adds GroovyParser (#662)
  pom.xml
  src/main/java/org/openrewrite/maven/ResourceParser.java
Labels: enhancement

#660 Avoid calling parsers when there are no source files
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Labels: bug

#665 Simplify logic surrounding building of Java & Kotlin parsers.
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Labels: enhancement

#669 Bump versions missed by other tools
  pom.xml
Labels: dependencies
