Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2023-07, with the labels that each got.

#592 Add `rewrite-bom` BOM dependency
  pom.xml
Labels: enhancement

#594 Use java.specification.version when no source and target version exists
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/test/java/org/openrewrite/maven/MavenMojoProjectParserTest.java
Labels: enhancement

#596 Add license headers and `license-maven-plugin`
  .mvn/licenseHeader.txt
  pom.xml
  src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
  src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
  src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
  src/main/java/org/openrewrite/maven/ArtifactResolver.java
  src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
  src/main/java/org/openrewrite/maven/ConfigureMojo.java
  src/main/java/org/openrewrite/maven/CycloneDxBomMojo.java
  src/main/java/org/openrewrite/maven/InitMojo.java
  src/main/java/org/openrewrite/maven/MavenLoggingMeterRegistry.java
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/main/java/org/openrewrite/maven/MeterRegistryProvider.java
  src/main/java/org/openrewrite/maven/RemoveMojo.java
  src/main/java/org/openrewrite/maven/ResourceParser.java
  src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
  src/main/java/org/openrewrite/maven/RewriteDryRunMojo.java
  src/main/java/org/openrewrite/maven/RewriteDryRunNoForkMojo.java
  src/main/java/org/openrewrite/maven/RewriteDumpMavenSettings.java
  src/main/java/org/openrewrite/maven/RewriteRunMojo.java
  src/main/java/org/openrewrite/maven/RewriteRunNoForkMojo.java
  src/main/java/org/openrewrite/maven/SanitizedMarkerPrinter.java
  src/main/java/org/openrewrite/maven/package-info.java
  src/main/java/org/openrewrite/maven/ui/RecipeDescriptorTree.java
  src/main/java/org/openrewrite/maven/ui/RecipeDescriptorTreePrompter.java
  src/main/java/org/openrewrite/maven/ui/package-info.java
  src/test/java/org/openrewrite/maven/AbstractRewriteMojoTest.java
  src/test/java/org/openrewrite/maven/BasicIT.java
  src/test/java/org/openrewrite/maven/ConfigureMojoIT.java
  src/test/java/org/openrewrite/maven/DiscoverNoActiveRecipeIT.java
  src/test/java/org/openrewrite/maven/InitMojoIT.java
  src/test/java/org/openrewrite/maven/MavenCLIExtra.java
  src/test/java/org/openrewrite/maven/RemoveMojoIT.java
  src/test/java/org/openrewrite/maven/RewriteCycloneDxIT.java
  src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
  src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
  src/test/java/org/openrewrite/maven/RewriteRunIT.java
Labels: enhancement

#606 Update the pom.xml so auto-generation works for docs
  pom.xml
  src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
  src/test/java/org/openrewrite/maven/RewriteRunIT.java
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/pom.xml
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/rewrite.yml
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/pom.xml
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/rewrite.yml
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/pom.xml
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/rewrite.yml
Labels: documentation

#607 Drop `init` and `configure` goals
  pom.xml
  src/main/java/org/openrewrite/maven/ConfigureMojo.java
  src/main/java/org/openrewrite/maven/InitMojo.java
  src/main/resources/version.txt
  src/test/java/org/openrewrite/maven/ConfigureMojoIT.java
  src/test/java/org/openrewrite/maven/InitMojoIT.java
  src/test/resources-its/org/openrewrite/maven/ConfigureMojoIT/single_project/pom.xml
  src/test/resources-its/org/openrewrite/maven/InitMojoIT/single_project/pom.xml
Labels: enhancement

#604 Allow the use of Java 17 in tests
  README.md
  pom.xml
Labels: enhancement

#603 Better adhere to plugin documentation recommendations
  pom.xml
Labels: documentation

#608 Deploy plugin docs to GitHub Pages
  .github/workflows/pages.yml
  pom.xml
Labels: documentation

#609 Remove unnecessary goal + grammar fixes for other goals
  src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
  src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
  src/main/java/org/openrewrite/maven/RemoveMojo.java
  src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
  src/main/java/org/openrewrite/maven/RewriteDumpMavenSettings.java
  src/test/java/org/openrewrite/maven/RemoveMojoIT.java
Labels: documentation, enhancement
