Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2024-10, with the labels that each got.

#872 Add rewrite-java-21 to support parsing Java 21+ projects
  pom.xml
Labels: dependencies

#882 Fix download snapshot warnings
  .gitignore
  src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/test/java/org/openrewrite/maven/BasicIT.java
  src/test/resources-its/org/openrewrite/maven/BasicIT/snapshot_ok/pom.xml
Labels: bug, enhancement

#887 Honor `rewrite.resolvePropertiesInYaml` flag in classpath scanning
  src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
Labels: enhancement
