Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2024-02, with the labels that each got.

#724 Standardize on `-Drewrite.` prefixed properties on the commandline
  src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
  src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
Labels: documentation, enhancement

#729 Separate JavaVersion markers for src/main and src/test
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/test/java/org/openrewrite/maven/MavenMojoProjectParserTest.java
Labels: bug, enhancement

#736 Pull up State to ConfigurableRewriteMojo for use in additional Mojo
  src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
  src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
Labels: enhancement

#725 Adding a logging resolution event listener
  src/main/java/org/openrewrite/maven/MavenLoggingResolutionEventListener.java
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Labels: enhancement

#741 Optionally resolve properties in yaml
  src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
Labels: bug, enhancement

#735 Clear `project.build.sourceEncoding` after parsing sources
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Labels: bug

#746 Add Maven BuildTool marker to .mvn/maven.config
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
Labels: enhancement
