Repository openrewrite/rewrite-maven-plugin, pull requests merged in 2025-01, with the labels that each got.

#922 Enable Develocity remote build cache on CI
  .github/workflows/ci.yml
  .gitignore
  .mvn/develocity.xml
  .mvn/extensions.xml
  .mvn/wrapper/maven-wrapper.properties
  pom.xml
  src/test/java/org/openrewrite/maven/BasicIT.java
  src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
Labels: enhancement, performance

#929 Restore headers & move license file to LICENSE folder
  .mvn/licenseHeader.txt
  LICENSE.md
  LICENSE/apache-license-v2.txt
  pom.xml
  src/main/java/org/openrewrite/maven/AbstractRewriteBaseRunMojo.java
  src/main/java/org/openrewrite/maven/AbstractRewriteDryRunMojo.java
  src/main/java/org/openrewrite/maven/AbstractRewriteMojo.java
  src/main/java/org/openrewrite/maven/AbstractRewriteRunMojo.java
  src/main/java/org/openrewrite/maven/ArtifactResolver.java
  src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java
  src/main/java/org/openrewrite/maven/LogLevel.java
  src/main/java/org/openrewrite/maven/MavenLoggingMeterRegistry.java
  src/main/java/org/openrewrite/maven/MavenLoggingResolutionEventListener.java
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/main/java/org/openrewrite/maven/MavenPomCacheBuilder.java
  src/main/java/org/openrewrite/maven/MeterRegistryProvider.java
  src/main/java/org/openrewrite/maven/ResourceParser.java
  src/main/java/org/openrewrite/maven/RewriteDiscoverMojo.java
  src/main/java/org/openrewrite/maven/RewriteDryRunMojo.java
  src/main/java/org/openrewrite/maven/RewriteDryRunNoForkMojo.java
  src/main/java/org/openrewrite/maven/RewriteRunMojo.java
  src/main/java/org/openrewrite/maven/RewriteRunNoForkMojo.java
  src/main/java/org/openrewrite/maven/SanitizedMarkerPrinter.java
  src/main/java/org/openrewrite/maven/package-info.java
  src/test/java/org/openrewrite/maven/AbstractRewriteMojoTest.java
  src/test/java/org/openrewrite/maven/BasicIT.java
  src/test/java/org/openrewrite/maven/DiscoverNoActiveRecipeIT.java
  src/test/java/org/openrewrite/maven/MavenCLIExtra.java
  src/test/java/org/openrewrite/maven/MavenMojoProjectParserTest.java
  src/test/java/org/openrewrite/maven/RewriteDiscoverIT.java
  src/test/java/org/openrewrite/maven/RewriteDryRunIT.java
  src/test/java/org/openrewrite/maven/RewriteRunIT.java
  src/test/java/org/openrewrite/maven/RewriteRunParallelIT.java
Labels: documentation

#935 Apply best practices on pull requests
  .github/workflows/comment-pr.yml
  .github/workflows/receive-pr.yml
  pom.xml
  rewrite.yml
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/a/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/no_plugin_in_pom/src/test/java/sample/SampleTest.java
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/single_project/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/checkstyle_inline_rules/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/java_compiler_plugin_project/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/multi_module_project/a/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/single_project/src/main/java/sample/EmptyBlockSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteRunIT/single_project/src/main/java/sample/SimplifyBooleanSample.java
  src/test/resources-its/org/openrewrite/maven/RewriteRunParallelIT/multi_module_project/a/src/main/java/sample/SimplifyBooleanSample.java
Labels: enhancement

#937 Make rewrite-maven-plugin search for Kotlin source files in src/*/java if src/*/kotlin does not exist
  src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java
  src/main/java/org/openrewrite/maven/package-info.java
  src/test/java/org/openrewrite/maven/KotlinIT.java
  src/test/resources-its/org/openrewrite/maven/KotlinIT/kotlin_in_src_main_java/pom.xml
  src/test/resources-its/org/openrewrite/maven/KotlinIT/kotlin_in_src_main_java/src/main/java/sample/MyClass.kt
  src/test/resources-its/org/openrewrite/maven/KotlinIT/kotlin_in_src_main_test/pom.xml
  src/test/resources-its/org/openrewrite/maven/KotlinIT/kotlin_in_src_main_test/src/test/java/sample/MyTest.kt
  src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/recipe_order/src/main/java/sample/EmptyBlockSample.java
Labels: enhancement, parser-maven
